### ISSUE TITLE
Channels stop playing after a few seconds

### ISSUE THREAD

**Issue by axelsimon** [ssapalski/plugin.audio.addict#7] opened 2017-09-26 12:37 UTC
OS:	Ubuntu 14.04.5 LTS
uname -a : Linux kodi 3.13.0-129-generic #178-Ubuntu SMP Fri Aug 11 12:48:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Kodi version: 2:17.4+git20170822.1009-final-0trusty
plugin.audio.addict version: v0.5.0 (2017-August-10)

Hi,
This started happening recently, the channels (from any network) start playing, stutter for a few seconds then just stop.

This shows up in the logs:
```
14:30:00.343 T:139757109511936   ERROR: /home/axx/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              SNIMissingWarning
14:30:00.343 T:139757109511936   ERROR: /home/kodi/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecurePlatformWarning
14:30:01.193 T:139760481925184  NOTICE: CVideoPlayer::CloseFile()
14:30:01.193 T:139760481925184  NOTICE: VideoPlayer: waiting for threads to exit
14:30:01.252 T:139757218453248  NOTICE: CVideoPlayer::OnExit()
14:30:01.252 T:139757218453248  NOTICE: Closing stream player 1
14:30:01.252 T:139757218453248  NOTICE: Waiting for audio thread to exit
14:30:01.261 T:139757298902784  NOTICE: thread end: CVideoPlayerAudio::OnExit()
14:30:01.261 T:139757218453248  NOTICE: Closing audio device
14:30:01.263 T:139757218453248  NOTICE: Deleting audio codec
14:30:01.672 T:139760481925184  NOTICE: VideoPlayer: finished waiting
14:30:01.672 T:139760481925184  NOTICE: VideoPlayer: Opening: http://prem2.di.fm:80/glitchhop_hi?xxx|User-Agent=Mozilla/5.0&Referer=http://www.di.fm/
14:30:01.701 T:139757218453248  NOTICE: Creating InputStream
14:30:02.340 T:139757218453248  NOTICE: Creating Demuxer
14:30:02.369 T:139757218453248  NOTICE: Opening stream: 0 source: 256
14:30:02.369 T:139757218453248  NOTICE: Finding audio codec for: 86017
14:30:02.369 T:139757218453248  NOTICE: Creating audio thread
14:30:02.370 T:139757138880256  NOTICE: running thread: CVideoPlayerAudio::Process()
14:30:02.381 T:139757138880256  NOTICE: Creating audio stream (codec id: 86017, channels: 2, sample rate: 44100, no pass-through)
14:30:02.459 T:139757218453248 WARNING: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
14:30:05.467 T:139757138880256  NOTICE: CVideoPlayerAudio::Process - stream stalled
 ```
Any ideas?

Thanks

**Comment by axelsimon** [comment] 2017-09-26 12:38
Just thought that I'd recently updated Kodi, but this started happening *after* the update, about 5 days ago I'd say.
And I checked, I actually added the Audio Addict plugin to Kodi on the day after I updated Kodi, so the Kodi update can't be to blame.

BTW, very nice plugin too, before I forget to mention it 😃

**Comment by axelsimon** [comment] 2017-10-12 13:48
Ok, this cleared up after reboot. Sorry for the useless issue, I think it can be safely closed.

**Comment by ssapalski** [comment] 2017-11-08 17:50
Sorry for the late reply, I will close this one now but open another ticket with a similar problem. Sometimes streams interrupt after several minutes to hours, I'll try to figure out the root cause but most likely it won't be connected to this one.

**Closed as completed by ssapalski** 2017-11-08 17:50 UTC
